id = "viewtree"
name = "ViewTree"
version = "1.0.2"
schema_version = 1
authors = ["Dev-cmyser <cmyser@example.com>"]
description = "Language Server Protocol (LSP) implementation for .view.tree files used in the $mol web framework."
repository = "https://github.com/Dev-cmyser/zed-view.tree-mol-support"

[grammars.viewtree]
repository = "file://../tree-sitter-viewtree"
rev = "HEAD"

[language_servers.view-tree-lsp]
name = "View.Tree LSP"
languages = ["ViewTree ($mol)"]

[language_servers.view-tree-lsp.language_ids]
"ViewTree ($mol)" = "view.tree"
