/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 76
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 48
#define ALIAS_COUNT 0
#define TOKEN_COUNT 25
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 8
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 9
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_newline = 1,
  sym_indent = 2,
  anon_sym_DASH = 3,
  aux_sym_remark_top_token1 = 4,
  sym_component_name = 5,
  sym_ident = 6,
  sym_prop_suffix = 7,
  sym_number = 8,
  anon_sym_true = 9,
  anon_sym_false = 10,
  sym_null_kw = 11,
  anon_sym_BSLASH = 12,
  sym_list_marker = 13,
  anon_sym_string = 14,
  anon_sym_number = 15,
  anon_sym_boolean = 16,
  sym_dict_marker = 17,
  sym_caret_line = 18,
  anon_sym_AT = 19,
  aux_sym_localized_string_token1 = 20,
  anon_sym_LT_EQ_GT = 21,
  anon_sym_LT_EQ = 22,
  anon_sym_EQ_GT = 23,
  anon_sym_SPACE = 24,
  sym_source_file = 25,
  sym_blank_line = 26,
  sym_remark_top = 27,
  sym_component_def = 28,
  sym_indented_node = 29,
  sym_property_id = 30,
  sym_boolean = 31,
  sym_primitive = 32,
  sym_string_literal = 33,
  sym_string_line = 34,
  sym_list_type = 35,
  sym_typed_list = 36,
  sym_remark_line = 37,
  sym_localized_string = 38,
  sym_value = 39,
  sym_bind_op = 40,
  sym_binding_rhs = 41,
  sym_dash_end = 42,
  sym_property_line = 43,
  sym_subcomponent_line = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_component_def_repeat1 = 46,
  aux_sym_subcomponent_line_repeat1 = 47,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_newline] = "newline",
  [sym_indent] = "indent",
  [anon_sym_DASH] = "-",
  [aux_sym_remark_top_token1] = "remark_top_token1",
  [sym_component_name] = "component_name",
  [sym_ident] = "ident",
  [sym_prop_suffix] = "prop_suffix",
  [sym_number] = "number",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [sym_null_kw] = "null_kw",
  [anon_sym_BSLASH] = "\\",
  [sym_list_marker] = "list_marker",
  [anon_sym_string] = "string",
  [anon_sym_number] = "number",
  [anon_sym_boolean] = "boolean",
  [sym_dict_marker] = "dict_marker",
  [sym_caret_line] = "caret_line",
  [anon_sym_AT] = "@",
  [aux_sym_localized_string_token1] = "localized_string_token1",
  [anon_sym_LT_EQ_GT] = "<=>",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_SPACE] = " ",
  [sym_source_file] = "source_file",
  [sym_blank_line] = "blank_line",
  [sym_remark_top] = "remark_top",
  [sym_component_def] = "component_def",
  [sym_indented_node] = "indented_node",
  [sym_property_id] = "property_id",
  [sym_boolean] = "boolean",
  [sym_primitive] = "primitive",
  [sym_string_literal] = "string_literal",
  [sym_string_line] = "string_line",
  [sym_list_type] = "list_type",
  [sym_typed_list] = "typed_list",
  [sym_remark_line] = "remark_line",
  [sym_localized_string] = "localized_string",
  [sym_value] = "value",
  [sym_bind_op] = "bind_op",
  [sym_binding_rhs] = "binding_rhs",
  [sym_dash_end] = "dash_end",
  [sym_property_line] = "property_line",
  [sym_subcomponent_line] = "subcomponent_line",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_component_def_repeat1] = "component_def_repeat1",
  [aux_sym_subcomponent_line_repeat1] = "subcomponent_line_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_newline] = sym_newline,
  [sym_indent] = sym_indent,
  [anon_sym_DASH] = anon_sym_DASH,
  [aux_sym_remark_top_token1] = aux_sym_remark_top_token1,
  [sym_component_name] = sym_component_name,
  [sym_ident] = sym_ident,
  [sym_prop_suffix] = sym_prop_suffix,
  [sym_number] = sym_number,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [sym_null_kw] = sym_null_kw,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [sym_list_marker] = sym_list_marker,
  [anon_sym_string] = anon_sym_string,
  [anon_sym_number] = anon_sym_number,
  [anon_sym_boolean] = anon_sym_boolean,
  [sym_dict_marker] = sym_dict_marker,
  [sym_caret_line] = sym_caret_line,
  [anon_sym_AT] = anon_sym_AT,
  [aux_sym_localized_string_token1] = aux_sym_localized_string_token1,
  [anon_sym_LT_EQ_GT] = anon_sym_LT_EQ_GT,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_source_file] = sym_source_file,
  [sym_blank_line] = sym_blank_line,
  [sym_remark_top] = sym_remark_top,
  [sym_component_def] = sym_component_def,
  [sym_indented_node] = sym_indented_node,
  [sym_property_id] = sym_property_id,
  [sym_boolean] = sym_boolean,
  [sym_primitive] = sym_primitive,
  [sym_string_literal] = sym_string_literal,
  [sym_string_line] = sym_string_line,
  [sym_list_type] = sym_list_type,
  [sym_typed_list] = sym_typed_list,
  [sym_remark_line] = sym_remark_line,
  [sym_localized_string] = sym_localized_string,
  [sym_value] = sym_value,
  [sym_bind_op] = sym_bind_op,
  [sym_binding_rhs] = sym_binding_rhs,
  [sym_dash_end] = sym_dash_end,
  [sym_property_line] = sym_property_line,
  [sym_subcomponent_line] = sym_subcomponent_line,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_component_def_repeat1] = aux_sym_component_def_repeat1,
  [aux_sym_subcomponent_line_repeat1] = aux_sym_subcomponent_line_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_newline] = {
    .visible = true,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_remark_top_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_component_name] = {
    .visible = true,
    .named = true,
  },
  [sym_ident] = {
    .visible = true,
    .named = true,
  },
  [sym_prop_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_number] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [sym_null_kw] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [sym_list_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_string] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_number] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_boolean] = {
    .visible = true,
    .named = false,
  },
  [sym_dict_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_caret_line] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_AT] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_localized_string_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LT_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_blank_line] = {
    .visible = true,
    .named = true,
  },
  [sym_remark_top] = {
    .visible = true,
    .named = true,
  },
  [sym_component_def] = {
    .visible = true,
    .named = true,
  },
  [sym_indented_node] = {
    .visible = true,
    .named = true,
  },
  [sym_property_id] = {
    .visible = true,
    .named = true,
  },
  [sym_boolean] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string_line] = {
    .visible = true,
    .named = true,
  },
  [sym_list_type] = {
    .visible = true,
    .named = true,
  },
  [sym_typed_list] = {
    .visible = true,
    .named = true,
  },
  [sym_remark_line] = {
    .visible = true,
    .named = true,
  },
  [sym_localized_string] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [sym_bind_op] = {
    .visible = true,
    .named = true,
  },
  [sym_binding_rhs] = {
    .visible = true,
    .named = true,
  },
  [sym_dash_end] = {
    .visible = true,
    .named = true,
  },
  [sym_property_line] = {
    .visible = true,
    .named = true,
  },
  [sym_subcomponent_line] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_def_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_subcomponent_line_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_base = 1,
  field_inline = 2,
  field_key = 3,
  field_name = 4,
  field_op = 5,
  field_rhs = 6,
  field_type = 7,
  field_value = 8,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_base] = "base",
  [field_inline] = "inline",
  [field_key] = "key",
  [field_name] = "name",
  [field_op] = "op",
  [field_rhs] = "rhs",
  [field_type] = "type",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 1},
  [3] = {.index = 3, .length = 2},
  [4] = {.index = 5, .length = 2},
  [5] = {.index = 7, .length = 3},
  [6] = {.index = 10, .length = 3},
  [7] = {.index = 13, .length = 1},
  [8] = {.index = 14, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_base, 1},
    {field_name, 0},
  [2] =
    {field_key, 0},
  [3] =
    {field_key, 0},
    {field_value, 1},
  [5] =
    {field_name, 1},
    {field_type, 2},
  [7] =
    {field_key, 0},
    {field_op, 1},
    {field_rhs, 2},
  [10] =
    {field_inline, 3, .inherited = true},
    {field_name, 1},
    {field_type, 2},
  [13] =
    {field_inline, 1},
  [14] =
    {field_inline, 0, .inherited = true},
    {field_inline, 1, .inherited = true},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 2,
  [4] = 4,
  [5] = 5,
  [6] = 5,
  [7] = 4,
  [8] = 8,
  [9] = 8,
  [10] = 10,
  [11] = 10,
  [12] = 5,
  [13] = 13,
  [14] = 14,
  [15] = 5,
  [16] = 16,
  [17] = 17,
  [18] = 14,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 25,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 36,
  [43] = 43,
  [44] = 44,
  [45] = 39,
  [46] = 33,
  [47] = 47,
  [48] = 48,
  [49] = 30,
  [50] = 50,
  [51] = 37,
  [52] = 32,
  [53] = 41,
  [54] = 28,
  [55] = 55,
  [56] = 48,
  [57] = 57,
  [58] = 58,
  [59] = 50,
  [60] = 60,
  [61] = 47,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 40,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 44,
  [72] = 58,
  [73] = 73,
  [74] = 74,
  [75] = 74,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '\t', 40,
        '\n', 39,
        '\r', 1,
        ' ', 110,
        '$', 84,
        '*', 102,
        '+', 13,
        '-', 42,
        '/', 98,
        '<', 10,
        '=', 12,
        '@', 104,
        'I', 67,
        'N', 48,
        '\\', 97,
        '^', 103,
        'b', 71,
        'f', 49,
        'n', 79,
        's', 78,
        't', 74,
        '!', 86,
        '?', 86,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(39);
      END_STATE();
    case 2:
      ADVANCE_MAP(
        '\n', 39,
        '\r', 1,
        ' ', 110,
        '$', 84,
        '-', 41,
        'b', 71,
        'n', 81,
        's', 78,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 3:
      ADVANCE_MAP(
        '\n', 39,
        '\r', 1,
        ' ', 110,
        '$', 36,
        '*', 102,
        '+', 13,
        '-', 42,
        '/', 98,
        '<', 10,
        '=', 12,
        '@', 104,
        'I', 25,
        'N', 15,
        '\\', 97,
        'f', 16,
        'n', 31,
        't', 27,
        '!', 86,
        '?', 86,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 4:
      ADVANCE_MAP(
        '\n', 39,
        '\r', 1,
        ' ', 110,
        '+', 13,
        '-', 42,
        '/', 98,
        'I', 25,
        'N', 15,
        '\\', 97,
        'f', 16,
        'n', 31,
        't', 27,
        '!', 86,
        '*', 86,
        '?', 86,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 5:
      ADVANCE_MAP(
        '\n', 39,
        '\r', 1,
        ' ', 105,
        '$', 84,
        '-', 41,
        'b', 71,
        'n', 81,
        's', 78,
      );
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 6:
      ADVANCE_MAP(
        '\n', 39,
        '\r', 1,
        ' ', 105,
        '$', 36,
        '*', 102,
        '+', 13,
        '-', 42,
        '/', 98,
        '<', 10,
        '=', 12,
        '@', 104,
        'I', 25,
        'N', 15,
        '\\', 97,
        'f', 16,
        'n', 31,
        't', 27,
        '!', 86,
        '?', 86,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 7:
      ADVANCE_MAP(
        '\n', 39,
        '\r', 1,
        ' ', 105,
        '+', 13,
        '-', 42,
        '/', 98,
        'I', 25,
        'N', 15,
        '\\', 97,
        'f', 16,
        'n', 31,
        't', 27,
        '!', 86,
        '*', 86,
        '?', 86,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 8:
      ADVANCE_MAP(
        ' ', 105,
        '$', 84,
        'I', 67,
        'N', 48,
        '\\', 97,
        'f', 49,
        'n', 82,
        't', 74,
        '+', 13,
        '-', 13,
      );
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 9:
      if (lookahead == ' ') ADVANCE(105);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '<') ADVANCE(11);
      if (lookahead == '\\') ADVANCE(97);
      if (lookahead == '^') ADVANCE(103);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 10:
      if (lookahead == '=') ADVANCE(108);
      END_STATE();
    case 11:
      if (lookahead == '=') ADVANCE(107);
      END_STATE();
    case 12:
      if (lookahead == '>') ADVANCE(109);
      END_STATE();
    case 13:
      if (lookahead == 'I') ADVANCE(25);
      if (lookahead == 'N') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 14:
      if (lookahead == 'N') ADVANCE(87);
      END_STATE();
    case 15:
      if (lookahead == 'a') ADVANCE(14);
      END_STATE();
    case 16:
      if (lookahead == 'a') ADVANCE(22);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(91);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(93);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(21);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 21:
      if (lookahead == 'i') ADVANCE(26);
      END_STATE();
    case 22:
      if (lookahead == 'l') ADVANCE(28);
      END_STATE();
    case 23:
      if (lookahead == 'l') ADVANCE(95);
      END_STATE();
    case 24:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 25:
      if (lookahead == 'n') ADVANCE(19);
      END_STATE();
    case 26:
      if (lookahead == 'n') ADVANCE(20);
      END_STATE();
    case 27:
      if (lookahead == 'r') ADVANCE(30);
      END_STATE();
    case 28:
      if (lookahead == 's') ADVANCE(18);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(32);
      END_STATE();
    case 30:
      if (lookahead == 'u') ADVANCE(17);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(24);
      END_STATE();
    case 32:
      if (lookahead == 'y') ADVANCE(87);
      END_STATE();
    case 33:
      if (lookahead == '+' ||
          lookahead == '-') ADVANCE(35);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 34:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 35:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 36:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '\t') ADVANCE(40);
      if (lookahead == '\n') ADVANCE(39);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(105);
      if (lookahead == '$') ADVANCE(36);
      if (lookahead == '-') ADVANCE(41);
      if (lookahead == '\\') ADVANCE(97);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_newline);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_indent);
      if (lookahead == '\t') ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_DASH);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_DASH);
      if (lookahead == 'I') ADVANCE(25);
      if (lookahead == 'N') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(aux_sym_remark_top_token1);
      if (lookahead == ' ') ADVANCE(43);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(aux_sym_remark_top_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_component_name);
      if (lookahead == '$' ||
          lookahead == '-') ADVANCE(85);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(sym_component_name);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(46);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'N') ADVANCE(85);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(47);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(61);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'a') ADVANCE(69);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'b') ADVANCE(55);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(92);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(94);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'e') ADVANCE(73);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'f') ADVANCE(58);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'g') ADVANCE(99);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(70);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(77);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'i') ADVANCE(68);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(76);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(96);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(54);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(62);
      if (lookahead == 'm') ADVANCE(51);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'l') ADVANCE(62);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'm') ADVANCE(51);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(56);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(57);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(101);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'n') ADVANCE(59);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(72);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'o') ADVANCE(63);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(100);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(80);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'r') ADVANCE(60);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 's') ADVANCE(53);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(83);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 't') ADVANCE(75);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(64);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(52);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(66);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'u') ADVANCE(65);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == 'y') ADVANCE(85);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9')) ADVANCE(85);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(45);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_ident);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_prop_suffix);
      if (lookahead == '!' ||
          lookahead == '*' ||
          lookahead == '?') ADVANCE(86);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_number);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == '.') ADVANCE(34);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(88);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_number);
      if (lookahead == 'E' ||
          lookahead == 'e') ADVANCE(33);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(89);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_number);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(90);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(sym_null_kw);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(sym_null_kw);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(sym_list_marker);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_string);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_number);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_boolean);
      if (lookahead == '$' ||
          lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(sym_dict_marker);
      if (lookahead == '!' ||
          lookahead == '*' ||
          lookahead == '?') ADVANCE(86);
      END_STATE();
    case 103:
      ACCEPT_TOKEN(sym_caret_line);
      END_STATE();
    case 104:
      ACCEPT_TOKEN(anon_sym_AT);
      END_STATE();
    case 105:
      ACCEPT_TOKEN(aux_sym_localized_string_token1);
      if (lookahead == ' ') ADVANCE(105);
      END_STATE();
    case 106:
      ACCEPT_TOKEN(anon_sym_LT_EQ_GT);
      END_STATE();
    case 107:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 108:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (lookahead == '>') ADVANCE(106);
      END_STATE();
    case 109:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 110:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == ' ') ADVANCE(105);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 3},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 3},
  [5] = {.lex_state = 3},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 6},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 6},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 4},
  [13] = {.lex_state = 9},
  [14] = {.lex_state = 2},
  [15] = {.lex_state = 7},
  [16] = {.lex_state = 37},
  [17] = {.lex_state = 37},
  [18] = {.lex_state = 5},
  [19] = {.lex_state = 37},
  [20] = {.lex_state = 37},
  [21] = {.lex_state = 37},
  [22] = {.lex_state = 37},
  [23] = {.lex_state = 37},
  [24] = {.lex_state = 8},
  [25] = {.lex_state = 2},
  [26] = {.lex_state = 37},
  [27] = {.lex_state = 37},
  [28] = {.lex_state = 2},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 2},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 2},
  [33] = {.lex_state = 2},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 2},
  [37] = {.lex_state = 2},
  [38] = {.lex_state = 37},
  [39] = {.lex_state = 2},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 37},
  [42] = {.lex_state = 37},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 37},
  [46] = {.lex_state = 37},
  [47] = {.lex_state = 0},
  [48] = {.lex_state = 0},
  [49] = {.lex_state = 37},
  [50] = {.lex_state = 0},
  [51] = {.lex_state = 37},
  [52] = {.lex_state = 37},
  [53] = {.lex_state = 37},
  [54] = {.lex_state = 37},
  [55] = {.lex_state = 37},
  [56] = {.lex_state = 37},
  [57] = {.lex_state = 43},
  [58] = {.lex_state = 43},
  [59] = {.lex_state = 37},
  [60] = {.lex_state = 43},
  [61] = {.lex_state = 37},
  [62] = {.lex_state = 37},
  [63] = {.lex_state = 43},
  [64] = {.lex_state = 37},
  [65] = {.lex_state = 9},
  [66] = {.lex_state = 37},
  [67] = {.lex_state = 37},
  [68] = {.lex_state = 37},
  [69] = {.lex_state = 37},
  [70] = {.lex_state = 37},
  [71] = {.lex_state = 37},
  [72] = {.lex_state = 43},
  [73] = {.lex_state = 37},
  [74] = {.lex_state = 37},
  [75] = {.lex_state = 37},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_newline] = ACTIONS(1),
    [sym_indent] = ACTIONS(1),
    [anon_sym_DASH] = ACTIONS(1),
    [sym_component_name] = ACTIONS(1),
    [sym_ident] = ACTIONS(1),
    [sym_prop_suffix] = ACTIONS(1),
    [sym_number] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [sym_null_kw] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [sym_list_marker] = ACTIONS(1),
    [anon_sym_string] = ACTIONS(1),
    [anon_sym_number] = ACTIONS(1),
    [anon_sym_boolean] = ACTIONS(1),
    [sym_dict_marker] = ACTIONS(1),
    [sym_caret_line] = ACTIONS(1),
    [anon_sym_AT] = ACTIONS(1),
    [aux_sym_localized_string_token1] = ACTIONS(3),
    [anon_sym_LT_EQ_GT] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_SPACE] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(55),
    [sym_blank_line] = STATE(17),
    [sym_remark_top] = STATE(17),
    [sym_component_def] = STATE(17),
    [aux_sym_source_file_repeat1] = STATE(17),
    [ts_builtin_sym_end] = ACTIONS(5),
    [sym_newline] = ACTIONS(7),
    [anon_sym_DASH] = ACTIONS(9),
    [sym_component_name] = ACTIONS(11),
    [aux_sym_localized_string_token1] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 15,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(15), 1,
      sym_newline,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      sym_list_marker,
    ACTIONS(27), 1,
      anon_sym_AT,
    ACTIONS(31), 1,
      anon_sym_LT_EQ,
    ACTIONS(33), 1,
      anon_sym_SPACE,
    STATE(10), 1,
      sym_bind_op,
    STATE(39), 1,
      sym_boolean,
    STATE(47), 1,
      sym_value,
    ACTIONS(17), 2,
      sym_component_name,
      sym_dict_marker,
    ACTIONS(19), 2,
      sym_number,
      sym_null_kw,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(29), 2,
      anon_sym_LT_EQ_GT,
      anon_sym_EQ_GT,
    STATE(44), 4,
      sym_primitive,
      sym_string_literal,
      sym_typed_list,
      sym_localized_string,
  [53] = 14,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(15), 1,
      sym_newline,
    ACTIONS(31), 1,
      anon_sym_LT_EQ,
    ACTIONS(41), 1,
      anon_sym_BSLASH,
    ACTIONS(43), 1,
      sym_list_marker,
    ACTIONS(45), 1,
      anon_sym_AT,
    STATE(11), 1,
      sym_bind_op,
    STATE(45), 1,
      sym_boolean,
    STATE(61), 1,
      sym_value,
    ACTIONS(29), 2,
      anon_sym_LT_EQ_GT,
      anon_sym_EQ_GT,
    ACTIONS(35), 2,
      sym_component_name,
      sym_dict_marker,
    ACTIONS(37), 2,
      sym_number,
      sym_null_kw,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(71), 4,
      sym_primitive,
      sym_string_literal,
      sym_typed_list,
      sym_localized_string,
  [103] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(49), 3,
      anon_sym_DASH,
      anon_sym_LT_EQ,
      anon_sym_SPACE,
    ACTIONS(47), 12,
      sym_newline,
      sym_component_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null_kw,
      anon_sym_BSLASH,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_AT,
      anon_sym_LT_EQ_GT,
      anon_sym_EQ_GT,
  [126] = 4,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(53), 1,
      sym_prop_suffix,
    ACTIONS(55), 3,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_SPACE,
    ACTIONS(51), 11,
      sym_newline,
      sym_component_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null_kw,
      anon_sym_BSLASH,
      sym_list_marker,
      anon_sym_AT,
      anon_sym_LT_EQ_GT,
      anon_sym_EQ_GT,
  [151] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(57), 1,
      sym_prop_suffix,
    ACTIONS(55), 2,
      sym_dict_marker,
      anon_sym_LT_EQ,
    ACTIONS(51), 11,
      sym_newline,
      sym_component_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null_kw,
      anon_sym_BSLASH,
      sym_list_marker,
      anon_sym_AT,
      anon_sym_LT_EQ_GT,
      anon_sym_EQ_GT,
  [175] = 3,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(49), 2,
      anon_sym_DASH,
      anon_sym_LT_EQ,
    ACTIONS(47), 12,
      sym_newline,
      sym_component_name,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null_kw,
      anon_sym_BSLASH,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_AT,
      anon_sym_LT_EQ_GT,
      anon_sym_EQ_GT,
  [197] = 9,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(25), 1,
      sym_list_marker,
    ACTIONS(59), 1,
      sym_newline,
    STATE(39), 1,
      sym_boolean,
    ACTIONS(19), 2,
      sym_number,
      sym_null_kw,
    ACTIONS(21), 2,
      anon_sym_true,
      anon_sym_false,
    ACTIONS(61), 2,
      anon_sym_DASH,
      anon_sym_SPACE,
    STATE(36), 3,
      sym_primitive,
      sym_string_literal,
      sym_typed_list,
  [230] = 9,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(41), 1,
      anon_sym_BSLASH,
    ACTIONS(43), 1,
      sym_list_marker,
    ACTIONS(59), 1,
      sym_newline,
    ACTIONS(61), 1,
      anon_sym_DASH,
    STATE(45), 1,
      sym_boolean,
    ACTIONS(37), 2,
      sym_number,
      sym_null_kw,
    ACTIONS(39), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(42), 3,
      sym_primitive,
      sym_string_literal,
      sym_typed_list,
  [262] = 10,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    ACTIONS(63), 1,
      sym_component_name,
    ACTIONS(65), 1,
      sym_ident,
    STATE(8), 1,
      sym_property_id,
    STATE(25), 1,
      sym_binding_rhs,
    STATE(39), 1,
      sym_boolean,
    ACTIONS(67), 2,
      sym_number,
      sym_null_kw,
    ACTIONS(69), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(33), 2,
      sym_primitive,
      sym_string_literal,
  [296] = 10,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(41), 1,
      anon_sym_BSLASH,
    ACTIONS(71), 1,
      sym_component_name,
    ACTIONS(73), 1,
      sym_ident,
    STATE(9), 1,
      sym_property_id,
    STATE(38), 1,
      sym_binding_rhs,
    STATE(45), 1,
      sym_boolean,
    ACTIONS(75), 2,
      sym_number,
      sym_null_kw,
    ACTIONS(77), 2,
      anon_sym_true,
      anon_sym_false,
    STATE(46), 2,
      sym_primitive,
      sym_string_literal,
  [330] = 4,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(79), 1,
      sym_prop_suffix,
    ACTIONS(55), 2,
      anon_sym_DASH,
      anon_sym_SPACE,
    ACTIONS(51), 7,
      sym_newline,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null_kw,
      anon_sym_BSLASH,
      sym_list_marker,
  [350] = 8,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(81), 1,
      anon_sym_DASH,
    ACTIONS(83), 1,
      sym_ident,
    ACTIONS(85), 1,
      anon_sym_BSLASH,
    ACTIONS(87), 1,
      sym_caret_line,
    ACTIONS(89), 1,
      anon_sym_LT_EQ,
    STATE(3), 1,
      sym_property_id,
    STATE(64), 4,
      sym_string_line,
      sym_remark_line,
      sym_property_line,
      sym_subcomponent_line,
  [378] = 5,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(95), 1,
      anon_sym_SPACE,
    STATE(32), 1,
      sym_list_type,
    ACTIONS(91), 2,
      sym_newline,
      anon_sym_DASH,
    ACTIONS(93), 5,
      sym_component_name,
      sym_ident,
      anon_sym_string,
      anon_sym_number,
      anon_sym_boolean,
  [399] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(55), 1,
      anon_sym_DASH,
    ACTIONS(97), 1,
      sym_prop_suffix,
    ACTIONS(51), 7,
      sym_newline,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null_kw,
      anon_sym_BSLASH,
      sym_list_marker,
  [418] = 6,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(99), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 1,
      sym_newline,
    ACTIONS(104), 1,
      anon_sym_DASH,
    ACTIONS(107), 1,
      sym_component_name,
    STATE(16), 4,
      sym_blank_line,
      sym_remark_top,
      sym_component_def,
      aux_sym_source_file_repeat1,
  [440] = 6,
    ACTIONS(7), 1,
      sym_newline,
    ACTIONS(9), 1,
      anon_sym_DASH,
    ACTIONS(11), 1,
      sym_component_name,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    STATE(16), 4,
      sym_blank_line,
      sym_remark_top,
      sym_component_def,
      aux_sym_source_file_repeat1,
  [462] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    STATE(52), 1,
      sym_list_type,
    ACTIONS(91), 2,
      sym_newline,
      anon_sym_DASH,
    ACTIONS(112), 5,
      sym_component_name,
      sym_ident,
      anon_sym_string,
      anon_sym_number,
      anon_sym_boolean,
  [480] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(116), 1,
      sym_indent,
    STATE(20), 2,
      sym_indented_node,
      aux_sym_component_def_repeat1,
    ACTIONS(114), 4,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_DASH,
      sym_component_name,
  [497] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(116), 1,
      sym_indent,
    STATE(21), 2,
      sym_indented_node,
      aux_sym_component_def_repeat1,
    ACTIONS(118), 4,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_DASH,
      sym_component_name,
  [514] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(122), 1,
      sym_indent,
    STATE(21), 2,
      sym_indented_node,
      aux_sym_component_def_repeat1,
    ACTIONS(120), 4,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_DASH,
      sym_component_name,
  [531] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(116), 1,
      sym_indent,
    STATE(23), 2,
      sym_indented_node,
      aux_sym_component_def_repeat1,
    ACTIONS(125), 4,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_DASH,
      sym_component_name,
  [548] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(116), 1,
      sym_indent,
    STATE(21), 2,
      sym_indented_node,
      aux_sym_component_def_repeat1,
    ACTIONS(127), 4,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_DASH,
      sym_component_name,
  [565] = 3,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(131), 1,
      anon_sym_BSLASH,
    ACTIONS(129), 6,
      sym_component_name,
      sym_ident,
      sym_number,
      anon_sym_true,
      anon_sym_false,
      sym_null_kw,
  [580] = 5,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(133), 1,
      sym_newline,
    ACTIONS(135), 1,
      anon_sym_DASH,
    ACTIONS(137), 1,
      anon_sym_SPACE,
    STATE(40), 1,
      sym_dash_end,
  [596] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(139), 4,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_DASH,
      sym_component_name,
  [606] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(141), 4,
      ts_builtin_sym_end,
      sym_newline,
      anon_sym_DASH,
      sym_component_name,
  [616] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(145), 1,
      anon_sym_SPACE,
    ACTIONS(143), 2,
      sym_newline,
      anon_sym_DASH,
  [627] = 4,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(147), 1,
      sym_newline,
    ACTIONS(149), 1,
      anon_sym_SPACE,
    STATE(34), 1,
      aux_sym_subcomponent_line_repeat1,
  [640] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(153), 1,
      anon_sym_SPACE,
    ACTIONS(151), 2,
      sym_newline,
      anon_sym_DASH,
  [651] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(155), 1,
      sym_ident,
    STATE(2), 1,
      sym_property_id,
    STATE(43), 1,
      sym_property_line,
  [664] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(159), 1,
      anon_sym_SPACE,
    ACTIONS(157), 2,
      sym_newline,
      anon_sym_DASH,
  [675] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(61), 1,
      anon_sym_SPACE,
    ACTIONS(59), 2,
      sym_newline,
      anon_sym_DASH,
  [686] = 4,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(161), 1,
      sym_newline,
    ACTIONS(163), 1,
      anon_sym_SPACE,
    STATE(34), 1,
      aux_sym_subcomponent_line_repeat1,
  [699] = 4,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(149), 1,
      anon_sym_SPACE,
    ACTIONS(166), 1,
      sym_newline,
    STATE(29), 1,
      aux_sym_subcomponent_line_repeat1,
  [712] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(170), 1,
      anon_sym_SPACE,
    ACTIONS(168), 2,
      sym_newline,
      anon_sym_DASH,
  [723] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(174), 1,
      anon_sym_SPACE,
    ACTIONS(172), 2,
      sym_newline,
      anon_sym_DASH,
  [734] = 4,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(133), 1,
      sym_newline,
    ACTIONS(176), 1,
      anon_sym_DASH,
    STATE(66), 1,
      sym_dash_end,
  [747] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(180), 1,
      anon_sym_SPACE,
    ACTIONS(178), 2,
      sym_newline,
      anon_sym_DASH,
  [758] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(182), 1,
      sym_newline,
    ACTIONS(184), 1,
      anon_sym_SPACE,
  [768] = 3,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(23), 1,
      anon_sym_BSLASH,
    STATE(48), 1,
      sym_string_literal,
  [778] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(168), 2,
      sym_newline,
      anon_sym_DASH,
  [786] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(186), 1,
      sym_newline,
    ACTIONS(188), 1,
      anon_sym_SPACE,
  [796] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(190), 1,
      sym_newline,
    ACTIONS(192), 1,
      anon_sym_SPACE,
  [806] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(178), 2,
      sym_newline,
      anon_sym_DASH,
  [814] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(59), 2,
      sym_newline,
      anon_sym_DASH,
  [822] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(194), 1,
      sym_newline,
    ACTIONS(196), 1,
      anon_sym_SPACE,
  [832] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(198), 1,
      sym_newline,
    ACTIONS(200), 1,
      anon_sym_SPACE,
  [842] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(151), 2,
      sym_newline,
      anon_sym_DASH,
  [850] = 3,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(202), 1,
      sym_newline,
    ACTIONS(204), 1,
      anon_sym_SPACE,
  [860] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(172), 2,
      sym_newline,
      anon_sym_DASH,
  [868] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(157), 2,
      sym_newline,
      anon_sym_DASH,
  [876] = 3,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(41), 1,
      anon_sym_BSLASH,
    STATE(56), 1,
      sym_string_literal,
  [886] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(143), 2,
      sym_newline,
      anon_sym_DASH,
  [894] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(206), 1,
      ts_builtin_sym_end,
  [901] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(198), 1,
      sym_newline,
  [908] = 2,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(208), 1,
      aux_sym_remark_top_token1,
  [915] = 2,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(210), 1,
      aux_sym_remark_top_token1,
  [922] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(202), 1,
      sym_newline,
  [929] = 2,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(212), 1,
      aux_sym_remark_top_token1,
  [936] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(194), 1,
      sym_newline,
  [943] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(214), 1,
      sym_component_name,
  [950] = 2,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(216), 1,
      aux_sym_remark_top_token1,
  [957] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(218), 1,
      sym_newline,
  [964] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(220), 1,
      sym_ident,
  [971] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(182), 1,
      sym_newline,
  [978] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(222), 1,
      sym_newline,
  [985] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(224), 1,
      sym_newline,
  [992] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(226), 1,
      sym_newline,
  [999] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(228), 1,
      sym_component_name,
  [1006] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(190), 1,
      sym_newline,
  [1013] = 2,
    ACTIONS(3), 1,
      aux_sym_localized_string_token1,
    ACTIONS(230), 1,
      aux_sym_remark_top_token1,
  [1020] = 2,
    ACTIONS(13), 1,
      aux_sym_localized_string_token1,
    ACTIONS(232), 1,
      sym_newline,
  [1027] = 1,
    ACTIONS(234), 1,
      aux_sym_localized_string_token1,
  [1031] = 1,
    ACTIONS(236), 1,
      aux_sym_localized_string_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 53,
  [SMALL_STATE(4)] = 103,
  [SMALL_STATE(5)] = 126,
  [SMALL_STATE(6)] = 151,
  [SMALL_STATE(7)] = 175,
  [SMALL_STATE(8)] = 197,
  [SMALL_STATE(9)] = 230,
  [SMALL_STATE(10)] = 262,
  [SMALL_STATE(11)] = 296,
  [SMALL_STATE(12)] = 330,
  [SMALL_STATE(13)] = 350,
  [SMALL_STATE(14)] = 378,
  [SMALL_STATE(15)] = 399,
  [SMALL_STATE(16)] = 418,
  [SMALL_STATE(17)] = 440,
  [SMALL_STATE(18)] = 462,
  [SMALL_STATE(19)] = 480,
  [SMALL_STATE(20)] = 497,
  [SMALL_STATE(21)] = 514,
  [SMALL_STATE(22)] = 531,
  [SMALL_STATE(23)] = 548,
  [SMALL_STATE(24)] = 565,
  [SMALL_STATE(25)] = 580,
  [SMALL_STATE(26)] = 596,
  [SMALL_STATE(27)] = 606,
  [SMALL_STATE(28)] = 616,
  [SMALL_STATE(29)] = 627,
  [SMALL_STATE(30)] = 640,
  [SMALL_STATE(31)] = 651,
  [SMALL_STATE(32)] = 664,
  [SMALL_STATE(33)] = 675,
  [SMALL_STATE(34)] = 686,
  [SMALL_STATE(35)] = 699,
  [SMALL_STATE(36)] = 712,
  [SMALL_STATE(37)] = 723,
  [SMALL_STATE(38)] = 734,
  [SMALL_STATE(39)] = 747,
  [SMALL_STATE(40)] = 758,
  [SMALL_STATE(41)] = 768,
  [SMALL_STATE(42)] = 778,
  [SMALL_STATE(43)] = 786,
  [SMALL_STATE(44)] = 796,
  [SMALL_STATE(45)] = 806,
  [SMALL_STATE(46)] = 814,
  [SMALL_STATE(47)] = 822,
  [SMALL_STATE(48)] = 832,
  [SMALL_STATE(49)] = 842,
  [SMALL_STATE(50)] = 850,
  [SMALL_STATE(51)] = 860,
  [SMALL_STATE(52)] = 868,
  [SMALL_STATE(53)] = 876,
  [SMALL_STATE(54)] = 886,
  [SMALL_STATE(55)] = 894,
  [SMALL_STATE(56)] = 901,
  [SMALL_STATE(57)] = 908,
  [SMALL_STATE(58)] = 915,
  [SMALL_STATE(59)] = 922,
  [SMALL_STATE(60)] = 929,
  [SMALL_STATE(61)] = 936,
  [SMALL_STATE(62)] = 943,
  [SMALL_STATE(63)] = 950,
  [SMALL_STATE(64)] = 957,
  [SMALL_STATE(65)] = 964,
  [SMALL_STATE(66)] = 971,
  [SMALL_STATE(67)] = 978,
  [SMALL_STATE(68)] = 985,
  [SMALL_STATE(69)] = 992,
  [SMALL_STATE(70)] = 999,
  [SMALL_STATE(71)] = 1006,
  [SMALL_STATE(72)] = 1013,
  [SMALL_STATE(73)] = 1020,
  [SMALL_STATE(74)] = 1027,
  [SMALL_STATE(75)] = 1031,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = false}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_line, 1, 0, 2),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(75),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [31] = {.entry = {.count = 1, .reusable = false}}, SHIFT(24),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_line, 1, 0, 2),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(54),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [47] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_id, 2, 0, 0),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_id, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_id, 1, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [55] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_id, 1, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding_rhs, 1, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding_rhs, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [65] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [67] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [69] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [71] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [73] = {.entry = {.count = 1, .reusable = false}}, SHIFT(15),
  [75] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(54),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [81] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(63),
  [87] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [89] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [91] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_list, 1, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typed_list, 1, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [99] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(57),
  [107] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(62),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, SHIFT(51),
  [114] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_def, 3, 0, 1),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [118] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_def, 4, 0, 1),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_def_repeat1, 2, 0, 0),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_component_def_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [125] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indented_node, 3, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_indented_node, 4, 0, 0),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_bind_op, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_bind_op, 1, 0, 0),
  [133] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_line, 3, 0, 5),
  [135] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_line, 3, 0, 5),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_blank_line, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_remark_top, 3, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_boolean, 1, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_boolean, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subcomponent_line, 4, 0, 6),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_typed_list, 2, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_typed_list, 2, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subcomponent_line_repeat1, 2, 0, 8),
  [163] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_subcomponent_line_repeat1, 2, 0, 8), SHIFT_REPEAT(31),
  [166] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_subcomponent_line, 3, 0, 4),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding_rhs, 2, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding_rhs, 2, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_list_type, 1, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_list_type, 1, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [178] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive, 1, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive, 1, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_line, 4, 0, 5),
  [184] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_line, 4, 0, 5),
  [186] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_subcomponent_line_repeat1, 2, 0, 7),
  [188] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_subcomponent_line_repeat1, 2, 0, 7),
  [190] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [192] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_value, 1, 0, 0),
  [194] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_line, 2, 0, 3),
  [196] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_line, 2, 0, 3),
  [198] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_localized_string, 3, 0, 0),
  [200] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_localized_string, 3, 0, 0),
  [202] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dash_end, 1, 0, 0),
  [204] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dash_end, 1, 0, 0),
  [206] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [208] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [210] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [212] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [214] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [216] = {.entry = {.count = 1, .reusable = true}}, SHIFT(68),
  [218] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [220] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [222] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_remark_line, 2, 0, 0),
  [224] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_line, 2, 0, 0),
  [226] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [228] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [230] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [232] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [234] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [236] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_viewtree(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "viewtree",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
