/* Automatically generated by tree-sitter v0.25.3 (2a835ee029dca1c325e6f1c01dbce40396f6123e) */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 42
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 36
#define ALIAS_COUNT 0
#define TOKEN_COUNT 21
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_indent = 1,
  sym_css_variable = 2,
  sym_identifier = 3,
  sym_component_name = 4,
  sym_parameter_marker = 5,
  anon_sym_BSLASH = 6,
  aux_sym_string_literal_token1 = 7,
  anon_sym_true = 8,
  anon_sym_false = 9,
  anon_sym_null = 10,
  aux_sym_primitive_literal_token1 = 11,
  sym_list_marker = 12,
  sym_dict_marker = 13,
  sym_null_value = 14,
  anon_sym_LT_EQ = 15,
  anon_sym_EQ_GT = 16,
  anon_sym_LT_EQ_GT = 17,
  sym_localization_string = 18,
  anon_sym_SPACE = 19,
  sym_caret = 20,
  sym_source_file = 21,
  sym_component = 22,
  sym_property_name = 23,
  sym_parameter = 24,
  sym_string_literal = 25,
  sym_primitive_literal = 26,
  sym_binding = 27,
  sym_component_binding = 28,
  sym_component_declaration_with_inline = 29,
  sym_component_declaration = 30,
  sym_property = 31,
  sym_node = 32,
  aux_sym_source_file_repeat1 = 33,
  aux_sym_component_repeat1 = 34,
  aux_sym_component_declaration_repeat1 = 35,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_indent] = "indent",
  [sym_css_variable] = "css_variable",
  [sym_identifier] = "identifier",
  [sym_component_name] = "component_name",
  [sym_parameter_marker] = "parameter_marker",
  [anon_sym_BSLASH] = "\\",
  [aux_sym_string_literal_token1] = "string_literal_token1",
  [anon_sym_true] = "true",
  [anon_sym_false] = "false",
  [anon_sym_null] = "null",
  [aux_sym_primitive_literal_token1] = "primitive_literal_token1",
  [sym_list_marker] = "list_marker",
  [sym_dict_marker] = "dict_marker",
  [sym_null_value] = "null_value",
  [anon_sym_LT_EQ] = "<=",
  [anon_sym_EQ_GT] = "=>",
  [anon_sym_LT_EQ_GT] = "<=>",
  [sym_localization_string] = "localization_string",
  [anon_sym_SPACE] = " ",
  [sym_caret] = "caret",
  [sym_source_file] = "source_file",
  [sym_component] = "component",
  [sym_property_name] = "property_name",
  [sym_parameter] = "parameter",
  [sym_string_literal] = "string_literal",
  [sym_primitive_literal] = "primitive_literal",
  [sym_binding] = "binding",
  [sym_component_binding] = "component_binding",
  [sym_component_declaration_with_inline] = "component_declaration_with_inline",
  [sym_component_declaration] = "component_declaration",
  [sym_property] = "property",
  [sym_node] = "node",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_component_repeat1] = "component_repeat1",
  [aux_sym_component_declaration_repeat1] = "component_declaration_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_indent] = sym_indent,
  [sym_css_variable] = sym_css_variable,
  [sym_identifier] = sym_identifier,
  [sym_component_name] = sym_component_name,
  [sym_parameter_marker] = sym_parameter_marker,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [aux_sym_string_literal_token1] = aux_sym_string_literal_token1,
  [anon_sym_true] = anon_sym_true,
  [anon_sym_false] = anon_sym_false,
  [anon_sym_null] = anon_sym_null,
  [aux_sym_primitive_literal_token1] = aux_sym_primitive_literal_token1,
  [sym_list_marker] = sym_list_marker,
  [sym_dict_marker] = sym_dict_marker,
  [sym_null_value] = sym_null_value,
  [anon_sym_LT_EQ] = anon_sym_LT_EQ,
  [anon_sym_EQ_GT] = anon_sym_EQ_GT,
  [anon_sym_LT_EQ_GT] = anon_sym_LT_EQ_GT,
  [sym_localization_string] = sym_localization_string,
  [anon_sym_SPACE] = anon_sym_SPACE,
  [sym_caret] = sym_caret,
  [sym_source_file] = sym_source_file,
  [sym_component] = sym_component,
  [sym_property_name] = sym_property_name,
  [sym_parameter] = sym_parameter,
  [sym_string_literal] = sym_string_literal,
  [sym_primitive_literal] = sym_primitive_literal,
  [sym_binding] = sym_binding,
  [sym_component_binding] = sym_component_binding,
  [sym_component_declaration_with_inline] = sym_component_declaration_with_inline,
  [sym_component_declaration] = sym_component_declaration,
  [sym_property] = sym_property,
  [sym_node] = sym_node,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_component_repeat1] = aux_sym_component_repeat1,
  [aux_sym_component_declaration_repeat1] = aux_sym_component_declaration_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_indent] = {
    .visible = true,
    .named = true,
  },
  [sym_css_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_component_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter_marker] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_string_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_true] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_false] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_null] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_primitive_literal_token1] = {
    .visible = false,
    .named = false,
  },
  [sym_list_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_dict_marker] = {
    .visible = true,
    .named = true,
  },
  [sym_null_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_EQ_GT] = {
    .visible = true,
    .named = false,
  },
  [sym_localization_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SPACE] = {
    .visible = true,
    .named = false,
  },
  [sym_caret] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_component] = {
    .visible = true,
    .named = true,
  },
  [sym_property_name] = {
    .visible = true,
    .named = true,
  },
  [sym_parameter] = {
    .visible = true,
    .named = true,
  },
  [sym_string_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_primitive_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_component_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_component_declaration_with_inline] = {
    .visible = true,
    .named = true,
  },
  [sym_component_declaration] = {
    .visible = true,
    .named = true,
  },
  [sym_property] = {
    .visible = true,
    .named = true,
  },
  [sym_node] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_component_declaration_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 24,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 37,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '$', 42,
        '*', 58,
        '-', 60,
        '/', 57,
        '<', 4,
        '=', 6,
        '@', 18,
        '\\', 46,
        '^', 67,
        'f', 32,
        'n', 41,
        't', 38,
        '!', 45,
        '?', 45,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 1:
      if (lookahead == '$') ADVANCE(42);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '\\') ADVANCE(46);
      if (lookahead == 'f') ADVANCE(32);
      if (lookahead == 'n') ADVANCE(41);
      if (lookahead == 't') ADVANCE(38);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(59);
      if (lookahead == '<') ADVANCE(5);
      if (lookahead == '\\') ADVANCE(46);
      if (lookahead == '^') ADVANCE(67);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(3);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 4:
      if (lookahead == '=') ADVANCE(62);
      END_STATE();
    case 5:
      if (lookahead == '=') ADVANCE(61);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(63);
      END_STATE();
    case 7:
      if (lookahead == '\\') ADVANCE(22);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 8:
      if (lookahead == 'a') ADVANCE(11);
      END_STATE();
    case 9:
      if (lookahead == 'e') ADVANCE(49);
      END_STATE();
    case 10:
      if (lookahead == 'e') ADVANCE(51);
      END_STATE();
    case 11:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 12:
      if (lookahead == 'l') ADVANCE(53);
      END_STATE();
    case 13:
      if (lookahead == 'l') ADVANCE(12);
      END_STATE();
    case 14:
      if (lookahead == 'r') ADVANCE(16);
      END_STATE();
    case 15:
      if (lookahead == 's') ADVANCE(10);
      END_STATE();
    case 16:
      if (lookahead == 'u') ADVANCE(9);
      END_STATE();
    case 17:
      if (lookahead == 'u') ADVANCE(13);
      END_STATE();
    case 18:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(7);
      END_STATE();
    case 19:
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 20:
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 21:
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 22:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 23:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '\t', 29,
        '$', 42,
        '*', 58,
        '-', 2,
        '/', 57,
        '<', 4,
        '=', 6,
        '@', 18,
        '\\', 46,
        'f', 32,
        'n', 41,
        't', 38,
      );
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(23);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 24:
      if (eof) ADVANCE(28);
      ADVANCE_MAP(
        '\t', 29,
        '$', 20,
        '*', 58,
        '-', 2,
        '/', 57,
        '<', 4,
        '=', 6,
        '@', 18,
        '\\', 46,
        'f', 8,
        'n', 17,
        't', 14,
        '!', 45,
        '?', 45,
      );
      if (('\n' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(24);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 25:
      if (eof) ADVANCE(28);
      if (lookahead == '\t') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(66);
      if (lookahead == '$') ADVANCE(42);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(25);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 26:
      if (eof) ADVANCE(28);
      if (lookahead == '\t') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(66);
      if (lookahead == '$') ADVANCE(20);
      if (('\n' <= lookahead && lookahead <= '\r')) SKIP(26);
      END_STATE();
    case 27:
      if (eof) ADVANCE(28);
      if (lookahead == '$') ADVANCE(20);
      if (lookahead == '\\') ADVANCE(46);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(27);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(sym_indent);
      if (lookahead == '\t') ADVANCE(29);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(sym_indent);
      if (lookahead == '\t') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(sym_css_variable);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(31);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'a') ADVANCE(35);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('b' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(50);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'e') ADVANCE(52);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(39);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(54);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'l') ADVANCE(36);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'r') ADVANCE(40);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 's') ADVANCE(34);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(33);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'u') ADVANCE(37);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(43);
      if (lookahead == '$' ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(sym_component_name);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(44);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(sym_parameter_marker);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(47);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead)) ADVANCE(48);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(aux_sym_string_literal_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(48);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_true);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(anon_sym_true);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(anon_sym_false);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_false);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(anon_sym_null);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(anon_sym_null);
      if (lookahead == '$' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(43);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(aux_sym_primitive_literal_token1);
      if (lookahead == '.') ADVANCE(19);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_primitive_literal_token1);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_list_marker);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_dict_marker);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_null_value);
      if (lookahead == '-') ADVANCE(21);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_null_value);
      if (lookahead == '-') ADVANCE(21);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LT_EQ);
      if (lookahead == '>') ADVANCE(64);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_EQ_GT);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_LT_EQ_GT);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_localization_string);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(65);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_SPACE);
      if (lookahead == '\t') ADVANCE(30);
      if (lookahead == ' ') ADVANCE(66);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_caret);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 27},
  [2] = {.lex_state = 24},
  [3] = {.lex_state = 24},
  [4] = {.lex_state = 24},
  [5] = {.lex_state = 23},
  [6] = {.lex_state = 24},
  [7] = {.lex_state = 24},
  [8] = {.lex_state = 3},
  [9] = {.lex_state = 1},
  [10] = {.lex_state = 1},
  [11] = {.lex_state = 24},
  [12] = {.lex_state = 24},
  [13] = {.lex_state = 1},
  [14] = {.lex_state = 25},
  [15] = {.lex_state = 25},
  [16] = {.lex_state = 25},
  [17] = {.lex_state = 24},
  [18] = {.lex_state = 24},
  [19] = {.lex_state = 24},
  [20] = {.lex_state = 24},
  [21] = {.lex_state = 24},
  [22] = {.lex_state = 3},
  [23] = {.lex_state = 25},
  [24] = {.lex_state = 25},
  [25] = {.lex_state = 26},
  [26] = {.lex_state = 27},
  [27] = {.lex_state = 27},
  [28] = {.lex_state = 24},
  [29] = {.lex_state = 24},
  [30] = {.lex_state = 24},
  [31] = {.lex_state = 24},
  [32] = {.lex_state = 24},
  [33] = {.lex_state = 27},
  [34] = {.lex_state = 24},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 24},
  [37] = {.lex_state = 47},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 27},
  [41] = {.lex_state = 47},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_css_variable] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym_component_name] = ACTIONS(1),
    [sym_parameter_marker] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_true] = ACTIONS(1),
    [anon_sym_false] = ACTIONS(1),
    [anon_sym_null] = ACTIONS(1),
    [aux_sym_primitive_literal_token1] = ACTIONS(1),
    [sym_list_marker] = ACTIONS(1),
    [sym_dict_marker] = ACTIONS(1),
    [sym_null_value] = ACTIONS(1),
    [anon_sym_LT_EQ] = ACTIONS(1),
    [anon_sym_EQ_GT] = ACTIONS(1),
    [anon_sym_LT_EQ_GT] = ACTIONS(1),
    [sym_localization_string] = ACTIONS(1),
    [sym_caret] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(38),
    [sym_component] = STATE(26),
    [aux_sym_source_file_repeat1] = STATE(26),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_component_name] = ACTIONS(5),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(11), 1,
      sym_component_name,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    STATE(10), 1,
      sym_binding,
    ACTIONS(7), 2,
      ts_builtin_sym_end,
      sym_indent,
    STATE(31), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(17), 3,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
    ACTIONS(9), 4,
      sym_css_variable,
      sym_list_marker,
      sym_dict_marker,
      sym_localization_string,
    ACTIONS(15), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
  [35] = 8,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(23), 1,
      sym_component_name,
    STATE(9), 1,
      sym_binding,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      sym_indent,
    STATE(29), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(17), 3,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
    ACTIONS(15), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
    ACTIONS(21), 4,
      sym_css_variable,
      sym_list_marker,
      sym_dict_marker,
      sym_localization_string,
  [70] = 4,
    ACTIONS(29), 1,
      sym_parameter_marker,
    STATE(6), 1,
      sym_parameter,
    ACTIONS(25), 2,
      ts_builtin_sym_end,
      sym_indent,
    ACTIONS(27), 13,
      sym_css_variable,
      sym_component_name,
      anon_sym_BSLASH,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      sym_localization_string,
  [96] = 3,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_indent,
    ACTIONS(33), 13,
      sym_css_variable,
      sym_component_name,
      anon_sym_BSLASH,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      sym_localization_string,
  [119] = 2,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_indent,
    ACTIONS(39), 13,
      sym_css_variable,
      sym_component_name,
      anon_sym_BSLASH,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      sym_localization_string,
  [139] = 2,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      sym_indent,
    ACTIONS(43), 13,
      sym_css_variable,
      sym_component_name,
      anon_sym_BSLASH,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
      sym_list_marker,
      sym_dict_marker,
      anon_sym_LT_EQ,
      anon_sym_EQ_GT,
      anon_sym_LT_EQ_GT,
      sym_localization_string,
  [159] = 8,
    ACTIONS(47), 1,
      anon_sym_BSLASH,
    ACTIONS(49), 1,
      sym_null_value,
    ACTIONS(51), 1,
      anon_sym_LT_EQ,
    ACTIONS(53), 1,
      sym_caret,
    STATE(2), 1,
      sym_property_name,
    STATE(25), 1,
      sym_component_declaration,
    ACTIONS(45), 2,
      sym_css_variable,
      sym_identifier,
    STATE(17), 3,
      sym_string_literal,
      sym_component_declaration_with_inline,
      sym_property,
  [187] = 8,
    ACTIONS(45), 1,
      sym_css_variable,
    ACTIONS(47), 1,
      anon_sym_BSLASH,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(57), 1,
      sym_component_name,
    ACTIONS(59), 1,
      aux_sym_primitive_literal_token1,
    STATE(12), 1,
      sym_property_name,
    STATE(28), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(15), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
  [215] = 8,
    ACTIONS(21), 1,
      sym_component_name,
    ACTIONS(45), 1,
      sym_css_variable,
    ACTIONS(47), 1,
      anon_sym_BSLASH,
    ACTIONS(55), 1,
      sym_identifier,
    ACTIONS(59), 1,
      aux_sym_primitive_literal_token1,
    STATE(11), 1,
      sym_property_name,
    STATE(29), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(15), 3,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
  [243] = 5,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(63), 1,
      sym_component_name,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym_indent,
    STATE(28), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(15), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
  [264] = 5,
    ACTIONS(13), 1,
      anon_sym_BSLASH,
    ACTIONS(67), 1,
      sym_component_name,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_indent,
    STATE(30), 2,
      sym_string_literal,
      sym_primitive_literal,
    ACTIONS(15), 4,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
      aux_sym_primitive_literal_token1,
  [285] = 2,
    ACTIONS(69), 3,
      sym_css_variable,
      anon_sym_BSLASH,
      aux_sym_primitive_literal_token1,
    ACTIONS(71), 5,
      sym_identifier,
      sym_component_name,
      anon_sym_true,
      anon_sym_false,
      anon_sym_null,
  [298] = 4,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(77), 1,
      sym_identifier,
    STATE(15), 2,
      sym_component_binding,
      aux_sym_component_declaration_repeat1,
    ACTIONS(75), 3,
      sym_indent,
      sym_component_name,
      anon_sym_SPACE,
  [314] = 4,
    ACTIONS(77), 1,
      sym_identifier,
    ACTIONS(79), 1,
      ts_builtin_sym_end,
    STATE(16), 2,
      sym_component_binding,
      aux_sym_component_declaration_repeat1,
    ACTIONS(81), 3,
      sym_indent,
      sym_component_name,
      anon_sym_SPACE,
  [330] = 4,
    ACTIONS(83), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 1,
      sym_identifier,
    STATE(16), 2,
      sym_component_binding,
      aux_sym_component_declaration_repeat1,
    ACTIONS(85), 3,
      sym_indent,
      sym_component_name,
      anon_sym_SPACE,
  [346] = 4,
    ACTIONS(90), 1,
      ts_builtin_sym_end,
    ACTIONS(92), 1,
      sym_indent,
    ACTIONS(94), 1,
      sym_component_name,
    STATE(21), 2,
      sym_node,
      aux_sym_component_repeat1,
  [360] = 4,
    ACTIONS(92), 1,
      sym_indent,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 1,
      sym_component_name,
    STATE(20), 2,
      sym_node,
      aux_sym_component_repeat1,
  [374] = 4,
    ACTIONS(92), 1,
      sym_indent,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 1,
      sym_component_name,
    STATE(18), 2,
      sym_node,
      aux_sym_component_repeat1,
  [388] = 4,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 1,
      sym_indent,
    ACTIONS(109), 1,
      sym_component_name,
    STATE(20), 2,
      sym_node,
      aux_sym_component_repeat1,
  [402] = 4,
    ACTIONS(92), 1,
      sym_indent,
    ACTIONS(111), 1,
      ts_builtin_sym_end,
    ACTIONS(113), 1,
      sym_component_name,
    STATE(20), 2,
      sym_node,
      aux_sym_component_repeat1,
  [416] = 4,
    ACTIONS(53), 1,
      sym_caret,
    STATE(2), 1,
      sym_property_name,
    STATE(32), 1,
      sym_property,
    ACTIONS(45), 2,
      sym_css_variable,
      sym_identifier,
  [430] = 2,
    ACTIONS(115), 1,
      ts_builtin_sym_end,
    ACTIONS(117), 4,
      sym_indent,
      sym_identifier,
      sym_component_name,
      anon_sym_SPACE,
  [440] = 2,
    ACTIONS(119), 1,
      ts_builtin_sym_end,
    ACTIONS(121), 4,
      sym_indent,
      sym_identifier,
      sym_component_name,
      anon_sym_SPACE,
  [450] = 3,
    ACTIONS(123), 1,
      ts_builtin_sym_end,
    ACTIONS(127), 1,
      anon_sym_SPACE,
    ACTIONS(125), 2,
      sym_indent,
      sym_component_name,
  [461] = 3,
    ACTIONS(5), 1,
      sym_component_name,
    ACTIONS(129), 1,
      ts_builtin_sym_end,
    STATE(27), 2,
      sym_component,
      aux_sym_source_file_repeat1,
  [472] = 3,
    ACTIONS(131), 1,
      ts_builtin_sym_end,
    ACTIONS(133), 1,
      sym_component_name,
    STATE(27), 2,
      sym_component,
      aux_sym_source_file_repeat1,
  [483] = 2,
    ACTIONS(67), 1,
      sym_component_name,
    ACTIONS(65), 2,
      ts_builtin_sym_end,
      sym_indent,
  [491] = 2,
    ACTIONS(63), 1,
      sym_component_name,
    ACTIONS(61), 2,
      ts_builtin_sym_end,
      sym_indent,
  [499] = 2,
    ACTIONS(138), 1,
      sym_component_name,
    ACTIONS(136), 2,
      ts_builtin_sym_end,
      sym_indent,
  [507] = 2,
    ACTIONS(23), 1,
      sym_component_name,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      sym_indent,
  [515] = 2,
    ACTIONS(142), 1,
      sym_component_name,
    ACTIONS(140), 2,
      ts_builtin_sym_end,
      sym_indent,
  [523] = 3,
    ACTIONS(144), 1,
      sym_component_name,
    ACTIONS(146), 1,
      anon_sym_BSLASH,
    STATE(23), 1,
      sym_string_literal,
  [533] = 2,
    ACTIONS(150), 1,
      sym_component_name,
    ACTIONS(148), 2,
      ts_builtin_sym_end,
      sym_indent,
  [541] = 2,
    STATE(3), 1,
      sym_property_name,
    ACTIONS(45), 2,
      sym_css_variable,
      sym_identifier,
  [549] = 2,
    ACTIONS(121), 1,
      sym_component_name,
    ACTIONS(119), 2,
      ts_builtin_sym_end,
      sym_indent,
  [557] = 1,
    ACTIONS(152), 1,
      aux_sym_string_literal_token1,
  [561] = 1,
    ACTIONS(154), 1,
      ts_builtin_sym_end,
  [565] = 1,
    ACTIONS(156), 1,
      sym_identifier,
  [569] = 1,
    ACTIONS(158), 1,
      sym_component_name,
  [573] = 1,
    ACTIONS(160), 1,
      aux_sym_string_literal_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 35,
  [SMALL_STATE(4)] = 70,
  [SMALL_STATE(5)] = 96,
  [SMALL_STATE(6)] = 119,
  [SMALL_STATE(7)] = 139,
  [SMALL_STATE(8)] = 159,
  [SMALL_STATE(9)] = 187,
  [SMALL_STATE(10)] = 215,
  [SMALL_STATE(11)] = 243,
  [SMALL_STATE(12)] = 264,
  [SMALL_STATE(13)] = 285,
  [SMALL_STATE(14)] = 298,
  [SMALL_STATE(15)] = 314,
  [SMALL_STATE(16)] = 330,
  [SMALL_STATE(17)] = 346,
  [SMALL_STATE(18)] = 360,
  [SMALL_STATE(19)] = 374,
  [SMALL_STATE(20)] = 388,
  [SMALL_STATE(21)] = 402,
  [SMALL_STATE(22)] = 416,
  [SMALL_STATE(23)] = 430,
  [SMALL_STATE(24)] = 440,
  [SMALL_STATE(25)] = 450,
  [SMALL_STATE(26)] = 461,
  [SMALL_STATE(27)] = 472,
  [SMALL_STATE(28)] = 483,
  [SMALL_STATE(29)] = 491,
  [SMALL_STATE(30)] = 499,
  [SMALL_STATE(31)] = 507,
  [SMALL_STATE(32)] = 515,
  [SMALL_STATE(33)] = 523,
  [SMALL_STATE(34)] = 533,
  [SMALL_STATE(35)] = 541,
  [SMALL_STATE(36)] = 549,
  [SMALL_STATE(37)] = 557,
  [SMALL_STATE(38)] = 561,
  [SMALL_STATE(39)] = 565,
  [SMALL_STATE(40)] = 569,
  [SMALL_STATE(41)] = 573,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [7] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 1, 0, 0),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [11] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 1, 0, 0),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(13),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(29),
  [23] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 2, 0, 0),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_name, 1, 0, 0),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_name, 1, 0, 0),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 1, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = false}}, SHIFT(7),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property_name, 2, 0, 0),
  [39] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property_name, 2, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_parameter, 2, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_parameter, 2, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [55] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [57] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [59] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 3, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 4, 0, 0),
  [67] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 4, 0, 0),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_binding, 1, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_binding, 1, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [79] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration, 4, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration, 4, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_declaration_repeat1, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_declaration_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_component_declaration_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 2, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 2, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 2, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component, 1, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component, 1, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0), SHIFT_REPEAT(8),
  [109] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_component_repeat1, 2, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_node, 3, 0, 0),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_node, 3, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_binding, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_binding, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string_literal, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_string_literal, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration_with_inline, 1, 0, 0),
  [125] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration_with_inline, 1, 0, 0),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(22),
  [129] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_property, 5, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_property, 5, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_component_declaration_with_inline, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_component_declaration_with_inline, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_primitive_literal, 1, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_primitive_literal, 1, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [154] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [156] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [160] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_molviewtree(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "molviewtree",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
